version: '3'

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mallaoui/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mallaoui/data/wordpress
  
networks:
    inception:
      driver: bridge

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
  
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - "443:443"
    restart: always
  
  wordpress:
    container_name: wordpress
    image: wordpress
    networks:
      - inception
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress/
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
      - redis
  
  redis:
    container_name: redis
    image: redis
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build:
      context: ./requirements/bonus/redis/
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    restart: always

  static_page:
    container_name: static_page
    image: static_page
    networks:
      - inception
    build:
      context: ./requirements/bonus/static_page/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always

  ftp:
    container_name: ftp
    image: ftp
    networks:
      - inception
    env_file:
      - .env
    build:
      context: ./requirements/bonus/ftp/
      dockerfile: Dockerfile
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - wordpress:/var/ftp
    restart: always

  cadvisor:
    container_name: cadvisor
    image: advisor
    networks:
      - inception
    ports:
      - "8080:8080"
    build:
      context: ./requirements/bonus/cadvisor/
      dockerfile: Dockerfile
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
  
  adminer:
    container_name: adminer
    image: adminer
    build: 
      context: ./requirements/bonus/adminer/
      dockerfile: Dockerfile
    networks:
      - inception
    ports:
      - "9090:9090"
    depends_on:
      - mariadb
    restart: always
