version: '3'

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mallaoui/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mallaoui/data/wordpress
  
networks:
    inception:
      driver: bridge

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
  
  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - "443:443"
    restart: always
  
  wordpress:
    container_name: wordpress
    networks:
      - inception
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress/
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - mariadb

